import Provider from './provider'
import GlobalHeader from 'components/GlobalHeader';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <GlobalHeader />
        <div style={{ marginTop: 80 }}>
          <Provider>{children}</Provider>
        </div>
      </body>
    </html>
  )
}
